// vim: set sw=4 ts=4 sts=4 expandtab :

#ifndef _LLKA_STANDARD_RESIDUES_H
#define _LLKA_STANDARD_RESIDUES_H

#include <llka_structure.h>

#include "ntc_bones.hpp"

#include <algorithm>
#include <map>
#include <string>
#include <vector>

/*
 * IMPORTANT NOTE:
 * Contents of this file are mostly auto-generated. The logic used to find what compounds
 * can be treated as if they were standard residues is rather crude. Expect that some "standard" residues
 * listed here may require special care.
 */

namespace LLKAInternal {

    inline const std::map<LLKABones::ANString, LLKA_BaseKind> STANDARD_RESIDUES_BASES = {
    {  "0A", LLKA_PURINE },
    { "0AD", LLKA_PURINE },
    { "0AP", LLKA_PYRIMIDINE },
    { "0AV", LLKA_PURINE },
    {  "0C", LLKA_PYRIMIDINE },
    { "0DA", LLKA_PURINE },
    { "0DC", LLKA_PYRIMIDINE },
    { "0DG", LLKA_PURINE },
    { "0DT", LLKA_PYRIMIDINE },
    {  "0G", LLKA_PURINE },
    { "0SP", LLKA_PURINE },
    { "0UH", LLKA_PURINE },
    { "10C", LLKA_PYRIMIDINE },
    { "125", LLKA_PYRIMIDINE },
    { "126", LLKA_PYRIMIDINE },
    { "127", LLKA_PYRIMIDINE },
    { "12A", LLKA_PURINE },
    { "16B", LLKA_PYRIMIDINE },
    { "18M", LLKA_PURINE },
    { "18Q", LLKA_PYRIMIDINE },
    { "1AP", LLKA_PURINE },
    { "1CC", LLKA_PYRIMIDINE },
    { "1DP", LLKA_PURINE },
    { "1FC", LLKA_PYRIMIDINE },
    { "1MA", LLKA_PURINE },
    { "1MG", LLKA_PURINE },
    { "1SC", LLKA_PYRIMIDINE },
    { "1TW", LLKA_PURINE },
    { "1WA", LLKA_PURINE },
    { "2AT", LLKA_PYRIMIDINE },
    { "2AU", LLKA_PYRIMIDINE },
    { "2BD", LLKA_PURINE },
    { "2BT", LLKA_PYRIMIDINE },
    { "2BU", LLKA_PURINE },
    { "2EG", LLKA_PURINE },
    { "2FE", LLKA_PURINE },
    { "2FI", LLKA_PURINE },
    { "2GF", LLKA_PYRIMIDINE },
    { "2GT", LLKA_PYRIMIDINE },
    { "2IA", LLKA_PURINE },
    { "2JU", LLKA_PYRIMIDINE },
    { "2MA", LLKA_PURINE },
    { "2MG", LLKA_PURINE },
    { "2MU", LLKA_PYRIMIDINE },
    { "2NT", LLKA_PYRIMIDINE },
    { "2OT", LLKA_PYRIMIDINE },
    { "2PR", LLKA_PURINE },
    { "2SG", LLKA_PURINE },
    { "2ST", LLKA_PYRIMIDINE },
    { "3AU", LLKA_PYRIMIDINE },
    { "3ZO", LLKA_PURINE },
    { "45A", LLKA_PURINE },
    { "47C", LLKA_PYRIMIDINE },
    { "4AC", LLKA_PYRIMIDINE },
    { "4DU", LLKA_PURINE },
    { "4E9", LLKA_PURINE },
    { "4OC", LLKA_PYRIMIDINE },
    { "4PC", LLKA_PYRIMIDINE },
    { "4PD", LLKA_PYRIMIDINE },
    { "4PE", LLKA_PYRIMIDINE },
    { "4SU", LLKA_PYRIMIDINE },
    { "4U3", LLKA_PYRIMIDINE },
    { "574", LLKA_PURINE },
    { "5BU", LLKA_PYRIMIDINE },
    { "5CF", LLKA_PYRIMIDINE },
    { "5CM", LLKA_PYRIMIDINE },
    { "5DB", LLKA_PYRIMIDINE },
    { "5EJ", LLKA_PYRIMIDINE },
    { "5FC", LLKA_PYRIMIDINE },
    { "5FU", LLKA_PYRIMIDINE },
    { "5HC", LLKA_PYRIMIDINE },
    { "5HM", LLKA_PYRIMIDINE },
    { "5HU", LLKA_PYRIMIDINE },
    { "5IC", LLKA_PYRIMIDINE },
    { "5IT", LLKA_PYRIMIDINE },
    { "5IU", LLKA_PYRIMIDINE },
    { "5JO", LLKA_PURINE },
    { "5MC", LLKA_PYRIMIDINE },
    { "5MU", LLKA_PYRIMIDINE },
    { "5OC", LLKA_PYRIMIDINE },
    { "5PC", LLKA_PYRIMIDINE },
    { "5PY", LLKA_PYRIMIDINE },
    { "5SE", LLKA_PYRIMIDINE },
    { "63G", LLKA_PURINE },
    { "63H", LLKA_PURINE },
    { "6FC", LLKA_PYRIMIDINE },
    { "6HB", LLKA_PURINE },
    { "6IA", LLKA_PURINE },
    { "6MA", LLKA_PURINE },
    { "6MC", LLKA_PURINE },
    { "6MT", LLKA_PURINE },
    { "6MZ", LLKA_PURINE },
    { "6NW", LLKA_PURINE },
    { "6OG", LLKA_PURINE },
    { "6OO", LLKA_PYRIMIDINE },
    { "6PO", LLKA_PURINE },
    { "70U", LLKA_PYRIMIDINE },
    { "73W", LLKA_PYRIMIDINE },
    { "75B", LLKA_PYRIMIDINE },
    { "77Y", LLKA_PYRIMIDINE },
    { "7BG", LLKA_PURINE },
    { "7DA", LLKA_PURINE },
    { "7GU", LLKA_PURINE },
    { "7OK", LLKA_PYRIMIDINE },
    { "7S3", LLKA_PURINE },
    { "85Y", LLKA_PYRIMIDINE },
    { "8AH", LLKA_PURINE },
    { "8BA", LLKA_PURINE },
    { "8DT", LLKA_PYRIMIDINE },
    { "8FG", LLKA_PURINE },
    { "8OG", LLKA_PURINE },
    { "8Y9", LLKA_PURINE },
    { "92F", LLKA_PYRIMIDINE },
    { "94O", LLKA_PYRIMIDINE },
    { "9QV", LLKA_PYRIMIDINE },
    { "9SI", LLKA_PURINE },
    { "9SY", LLKA_PURINE },
    {   "A", LLKA_PURINE },
    { "A23", LLKA_PURINE },
    { "A2L", LLKA_PURINE },
    { "A2M", LLKA_PURINE },
    { "A34", LLKA_PURINE },
    { "A35", LLKA_PURINE },
    { "A40", LLKA_PURINE },
    { "A44", LLKA_PURINE },
    { "A47", LLKA_PURINE },
    { "A5L", LLKA_PURINE },
    { "A5M", LLKA_PYRIMIDINE },
    { "A5O", LLKA_PURINE },
    { "A9Z", LLKA_PURINE },
    { "ABR", LLKA_PURINE },
    { "ABS", LLKA_PURINE },
    { "AET", LLKA_PURINE },
    { "AF2", LLKA_PURINE },
    { "AFG", LLKA_PURINE },
    { "AP7", LLKA_PURINE },
    {  "AS", LLKA_PURINE },
    { "ATL", LLKA_PYRIMIDINE },
    { "ATP", LLKA_PURINE },
    { "AVC", LLKA_PURINE },
    { "AWC", LLKA_PYRIMIDINE },
    { "B7C", LLKA_PYRIMIDINE },
    { "B8T", LLKA_PYRIMIDINE },
    { "B8W", LLKA_PURINE },
    { "B9B", LLKA_PURINE },
    { "BMP", LLKA_PYRIMIDINE },
    { "BOE", LLKA_PYRIMIDINE },
    { "BRU", LLKA_PYRIMIDINE },
    { "BT5", LLKA_PURINE },
    { "BVP", LLKA_PYRIMIDINE },
    {   "C", LLKA_PYRIMIDINE },
    { "C25", LLKA_PYRIMIDINE },
    { "C2L", LLKA_PYRIMIDINE },
    { "C2S", LLKA_PYRIMIDINE },
    { "C31", LLKA_PYRIMIDINE },
    { "C32", LLKA_PYRIMIDINE },
    { "C34", LLKA_PYRIMIDINE },
    { "C37", LLKA_PYRIMIDINE },
    { "C38", LLKA_PYRIMIDINE },
    { "C43", LLKA_PYRIMIDINE },
    { "C45", LLKA_PYRIMIDINE },
    { "C46", LLKA_PYRIMIDINE },
    { "C5L", LLKA_PYRIMIDINE },
    { "C6G", LLKA_PURINE },
    { "C7R", LLKA_PYRIMIDINE },
    { "C7S", LLKA_PYRIMIDINE },
    { "CBR", LLKA_PYRIMIDINE },
    { "CBV", LLKA_PYRIMIDINE },
    { "CCC", LLKA_PYRIMIDINE },
    { "CFL", LLKA_PYRIMIDINE },
    { "CFZ", LLKA_PYRIMIDINE },
    { "CG1", LLKA_PURINE },
    {  "CH", LLKA_PYRIMIDINE },
    { "CM0", LLKA_PYRIMIDINE },
    { "CMR", LLKA_PYRIMIDINE },
    { "CNU", LLKA_PYRIMIDINE },
    { "CSL", LLKA_PYRIMIDINE },
    { "CX2", LLKA_PYRIMIDINE },
    { "D00", LLKA_PYRIMIDINE },
    {  "DA", LLKA_PURINE },
    {  "DC", LLKA_PYRIMIDINE },
    { "DCG", LLKA_PURINE },
    { "DDN", LLKA_PYRIMIDINE },
    { "DFG", LLKA_PURINE },
    {  "DG", LLKA_PURINE },
    { "DG8", LLKA_PURINE },
    { "DHU", LLKA_PYRIMIDINE },
    {  "DI", LLKA_PURINE },
    { "DJF", LLKA_PURINE },
    { "DNR", LLKA_PYRIMIDINE },
    {  "DP", LLKA_PURINE },
    {  "DT", LLKA_PYRIMIDINE },
    {  "DU", LLKA_PYRIMIDINE },
    { "DUZ", LLKA_PYRIMIDINE },
    {  "DX", LLKA_PURINE },
    { "DZM", LLKA_PURINE },
    {   "E", LLKA_PURINE },
    { "E1X", LLKA_PURINE },
    { "E6G", LLKA_PURINE },
    { "EDA", LLKA_PURINE },
    { "EDI", LLKA_PURINE },
    { "EHG", LLKA_PURINE },
    { "EIT", LLKA_PYRIMIDINE },
    { "EQ0", LLKA_PURINE },
    { "EWC", LLKA_PURINE },
    { "F3O", LLKA_PURINE },
    { "F74", LLKA_PURINE },
    { "FA5", LLKA_PURINE },
    { "FDG", LLKA_PURINE },
    { "FMG", LLKA_PURINE },
    { "FMU", LLKA_PYRIMIDINE },
    { "FNU", LLKA_PYRIMIDINE },
    {   "G", LLKA_PURINE },
    { "G25", LLKA_PURINE },
    { "G2L", LLKA_PURINE },
    { "G2S", LLKA_PURINE },
    { "G32", LLKA_PURINE },
    { "G33", LLKA_PURINE },
    { "G35", LLKA_PURINE },
    { "G36", LLKA_PURINE },
    { "G42", LLKA_PURINE },
    { "G46", LLKA_PURINE },
    { "G47", LLKA_PURINE },
    { "G48", LLKA_PURINE },
    { "G49", LLKA_PURINE },
    { "G7M", LLKA_PURINE },
    { "GAO", LLKA_PURINE },
    { "GCK", LLKA_PYRIMIDINE },
    { "GDP", LLKA_PURINE },
    { "GF2", LLKA_PURINE },
    { "GFL", LLKA_PURINE },
    { "GMS", LLKA_PURINE },
    { "GMU", LLKA_PYRIMIDINE },
    { "GNE", LLKA_PURINE },
    { "GOM", LLKA_PURINE },
    { "GRB", LLKA_PURINE },
    {  "GS", LLKA_PURINE },
    { "GSR", LLKA_PURINE },
    { "GSS", LLKA_PURINE },
    { "GTP", LLKA_PURINE },
    { "GX1", LLKA_PURINE },
    { "H2U", LLKA_PYRIMIDINE },
    { "HEU", LLKA_PYRIMIDINE },
    { "HN0", LLKA_PURINE },
    { "HN1", LLKA_PURINE },
    {   "I", LLKA_PURINE },
    { "I4U", LLKA_PYRIMIDINE },
    { "I5C", LLKA_PYRIMIDINE },
    {  "IG", LLKA_PURINE },
    { "IGU", LLKA_PURINE },
    {  "IU", LLKA_PYRIMIDINE },
    { "J0X", LLKA_PYRIMIDINE },
    { "JDT", LLKA_PYRIMIDINE },
    { "JW5", LLKA_PYRIMIDINE },
    { "KAG", LLKA_PURINE },
    { "LCA", LLKA_PURINE },
    { "LCG", LLKA_PURINE },
    { "LCH", LLKA_PYRIMIDINE },
    { "LGP", LLKA_PURINE },
    { "LHH", LLKA_PYRIMIDINE },
    { "LSH", LLKA_PYRIMIDINE },
    { "LST", LLKA_PYRIMIDINE },
    { "LV2", LLKA_PYRIMIDINE },
    { "M1G", LLKA_PURINE },
    { "M2G", LLKA_PURINE },
    { "M3O", LLKA_PURINE },
    { "M5M", LLKA_PYRIMIDINE },
    { "M7A", LLKA_PURINE },
    { "MA6", LLKA_PURINE },
    { "MA7", LLKA_PURINE },
    { "MAD", LLKA_PURINE },
    { "MDV", LLKA_PURINE },
    { "MG1", LLKA_PURINE },
    { "MGV", LLKA_PURINE },
    { "MIA", LLKA_PURINE },
    { "MMX", LLKA_PYRIMIDINE },
    { "MNU", LLKA_PYRIMIDINE },
    { "MRG", LLKA_PURINE },
    { "MUM", LLKA_PYRIMIDINE },
    { "N4S", LLKA_PYRIMIDINE },
    { "N5M", LLKA_PYRIMIDINE },
    { "N7X", LLKA_PYRIMIDINE },
    { "NCX", LLKA_PURINE },
    { "NDU", LLKA_PYRIMIDINE },
    { "NMS", LLKA_PYRIMIDINE },
    { "NMT", LLKA_PYRIMIDINE },
    { "O2G", LLKA_PURINE },
    { "O2Z", LLKA_PURINE },
    { "OFC", LLKA_PYRIMIDINE },
    { "OGX", LLKA_PURINE },
    { "OHU", LLKA_PYRIMIDINE },
    { "OIP", LLKA_PURINE },
    { "OKN", LLKA_PYRIMIDINE },
    { "OKT", LLKA_PYRIMIDINE },
    { "OMC", LLKA_PYRIMIDINE },
    { "OMG", LLKA_PURINE },
    { "OMU", LLKA_PYRIMIDINE },
    { "OWR", LLKA_PURINE },
    {   "P", LLKA_PURINE },
    { "P2T", LLKA_PYRIMIDINE },
    { "P4U", LLKA_PYRIMIDINE },
    { "P5P", LLKA_PURINE },
    { "PDU", LLKA_PYRIMIDINE },
    { "PG7", LLKA_PURINE },
    { "PGN", LLKA_PURINE },
    { "PGP", LLKA_PURINE },
    { "PPW", LLKA_PURINE },
    { "PR5", LLKA_PURINE },
    { "PRN", LLKA_PURINE },
    { "PST", LLKA_PYRIMIDINE },
    { "PYO", LLKA_PYRIMIDINE },
    { "QSK", LLKA_PYRIMIDINE },
    { "QSQ", LLKA_PURINE },
    { "QUO", LLKA_PURINE },
    {   "R", LLKA_PURINE },
    { "RBD", LLKA_PURINE },
    { "RDG", LLKA_PURINE },
    { "RFJ", LLKA_PURINE },
    { "RMP", LLKA_PURINE },
    { "RPC", LLKA_PYRIMIDINE },
    { "RSP", LLKA_PYRIMIDINE },
    { "RSQ", LLKA_PYRIMIDINE },
    {  "RT", LLKA_PYRIMIDINE },
    { "RUS", LLKA_PYRIMIDINE },
    {  "RY", LLKA_PYRIMIDINE },
    { "S2M", LLKA_PYRIMIDINE },
    { "S4U", LLKA_PYRIMIDINE },
    { "S6G", LLKA_PURINE },
    { "S6M", LLKA_PYRIMIDINE },
    {  "SC", LLKA_PYRIMIDINE },
    { "SDE", LLKA_PURINE },
    { "SDG", LLKA_PURINE },
    { "SDH", LLKA_PURINE },
    { "SMP", LLKA_PURINE },
    { "SMT", LLKA_PYRIMIDINE },
    { "SPT", LLKA_PYRIMIDINE },
    { "SRA", LLKA_PURINE },
    { "SSU", LLKA_PYRIMIDINE },
    { "SUR", LLKA_PYRIMIDINE },
    {   "T", LLKA_PYRIMIDINE },
    { "T0N", LLKA_PYRIMIDINE },
    { "T0Q", LLKA_PYRIMIDINE },
    { "T2S", LLKA_PYRIMIDINE },
    { "T31", LLKA_PYRIMIDINE },
    { "T36", LLKA_PYRIMIDINE },
    { "T38", LLKA_PYRIMIDINE },
    { "T39", LLKA_PYRIMIDINE },
    { "T41", LLKA_PYRIMIDINE },
    { "T4S", LLKA_PYRIMIDINE },
    { "T5O", LLKA_PYRIMIDINE },
    { "T5S", LLKA_PYRIMIDINE },
    { "T6A", LLKA_PURINE },
    { "TA3", LLKA_PYRIMIDINE },
    { "TAF", LLKA_PYRIMIDINE },
    { "TC1", LLKA_PYRIMIDINE },
    { "TCP", LLKA_PYRIMIDINE },
    { "TED", LLKA_PYRIMIDINE },
    { "TFE", LLKA_PYRIMIDINE },
    { "TGP", LLKA_PURINE },
    { "THX", LLKA_PYRIMIDINE },
    { "TPC", LLKA_PYRIMIDINE },
    {  "TS", LLKA_PYRIMIDINE },
    { "TTI", LLKA_PYRIMIDINE },
    { "TTM", LLKA_PYRIMIDINE },
    { "TX2", LLKA_PYRIMIDINE },
    {   "U", LLKA_PYRIMIDINE },
    { "U25", LLKA_PYRIMIDINE },
    { "U2L", LLKA_PYRIMIDINE },
    { "U2N", LLKA_PYRIMIDINE },
    { "U31", LLKA_PYRIMIDINE },
    { "U36", LLKA_PYRIMIDINE },
    { "U37", LLKA_PYRIMIDINE },
    { "U48", LLKA_PYRIMIDINE },
    { "U7B", LLKA_PYRIMIDINE },
    { "U8U", LLKA_PYRIMIDINE },
    { "UAR", LLKA_PYRIMIDINE },
    { "UBI", LLKA_PYRIMIDINE },
    { "UBR", LLKA_PYRIMIDINE },
    { "UCL", LLKA_PYRIMIDINE },
    { "UD5", LLKA_PYRIMIDINE },
    { "UFB", LLKA_PYRIMIDINE },
    { "UFP", LLKA_PYRIMIDINE },
    { "UFR", LLKA_PYRIMIDINE },
    { "UFT", LLKA_PYRIMIDINE },
    { "UMP", LLKA_PYRIMIDINE },
    { "UOA", LLKA_PYRIMIDINE },
    { "UPE", LLKA_PYRIMIDINE },
    { "UPS", LLKA_PYRIMIDINE },
    { "UPV", LLKA_PYRIMIDINE },
    { "US2", LLKA_PYRIMIDINE },
    { "US3", LLKA_PYRIMIDINE },
    { "US5", LLKA_PYRIMIDINE },
    { "UY4", LLKA_PURINE },
    { "V3L", LLKA_PURINE },
    { "VC7", LLKA_PURINE },
    {   "X", LLKA_PURINE },
    { "XCY", LLKA_PYRIMIDINE },
    { "XFC", LLKA_PYRIMIDINE },
    { "XNY", LLKA_PURINE },
    { "XPB", LLKA_PURINE },
    { "XUA", LLKA_PURINE },
    { "XUG", LLKA_PURINE },
    {   "Y", LLKA_PURINE },
    { "Y5P", LLKA_PYRIMIDINE },
    { "YCO", LLKA_PYRIMIDINE },
    {  "YG", LLKA_PURINE },
    { "YYG", LLKA_PURINE },
    {   "Z", LLKA_PYRIMIDINE },
    { "ZDU", LLKA_PYRIMIDINE }
};

inline const std::vector<LLKABones::ANString> PRIORITY_RESIDUES = {
    "A", "DA", "C", "DC", "G", "DG", "T", "U"
};

inline
auto priorityResidueComparator(const std::string &lhs, const std::string &rhs)
{
    auto prioLhs = std::find(PRIORITY_RESIDUES.cbegin(), PRIORITY_RESIDUES.cend(), lhs);
    auto prioRhs = std::find(PRIORITY_RESIDUES.cbegin(), PRIORITY_RESIDUES.cend(), rhs);

    if (prioLhs != PRIORITY_RESIDUES.cend()) {
        if (prioRhs != PRIORITY_RESIDUES.cend()) {
            return prioLhs < prioRhs;
        } else
            return true; // lhs is a priority residue, rhs is not. Prioritize lhs.
    } else if (prioRhs != PRIORITY_RESIDUES.cend())
        return false; // lhs is not a priority residue, rhs is. Prioritize rhs.

    return lhs < rhs;
}

static
auto initializeStandardResidues()
{
    std::vector<LLKABones::ANString> vec{};
    vec.reserve(STANDARD_RESIDUES_BASES.size());

    for (const auto &it : STANDARD_RESIDUES_BASES)
        vec.push_back(it.first);

    std::sort(vec.begin(), vec.end(), priorityResidueComparator);

    return vec;
}

inline const std::vector<LLKABones::ANString> KNOWN_STANDARD_RESIDUES = initializeStandardResidues();

} // namespace LLKAInternal

#endif // _LLKA_STANDARD_RESIDUES_H

